from __future__ import annotations

R_FUNCTIONS_WITH_DIRECT_COUNTERPARTS = [
    "calculate_gravy",
    "filterPeptides",
    "plot_cleavage_site",
    "plot_count",
    "plot_gravy_vs_intensity",
    "plot_int",
    "plot_length_distribution",
    "plot_pep_align",
    "plot_type_num",
    "plot_volcano",
    "processPeptides",
    "ttestPeptides",
]

PYTHON_ONLY_PARITY_HELPERS = {
    "load_example_protein_mapping": "Compare against the upstream R packaged dataset `peptidomics_protein_mapping_example`.",
}

STRUCTURED_PARITY_CASES = {
    "mapping_example_dataset": "Load the packaged example mapping and compare it to the upstream R dataset.",
    "calculate_gravy_examples": "Compare GRAVY scores for representative peptide strings against the upstream R helper.",
    "process_default": "Run processPeptides() with the canonical v1.1.1-alpha fixture files.",
    "filter_exact": "Compare exact-sequence filtering against R.",
    "filter_regex": "Compare regex filtering against R.",
    "filter_grouped": "Compare grouped filtering against R.",
    "filter_union": "Compare seqs + seq_pattern union semantics against R.",
    "ttest_plain_main": "Compare the main plain-mode contrast against R.",
    "ttest_plain_reordered": "Compare order-independent selector parsing against R.",
    "ttest_plain_explicit": "Compare explicit column=value selectors against R.",
    "ttest_plain_pooled": "Compare pooled partial selectors against R.",
    "ttest_plain_equalvar": "Compare equal_var=True plain mode against R.",
    "ttest_plain_custom_adjust": "Compare custom pseudocount + p-value adjustment against R.",
    "ttest_plain_min_reps": "Compare min_reps_per_side behavior against R.",
    "ttest_treat_main": "Compare the main treat-mode contrast against R.",
    "ttest_treat_custom_threshold": "Compare treat-mode alpha + lfc_thresh changes against R.",
}

PLOT_PARITY_CASES = {
    "plot_int_mean_named": "Mean-intensity bar plot with explicit x_var, filter_params, and Protein.name colors.",
    "plot_int_reps_default": "Replicate plot using default x_var and default Replicate faceting behavior.",
    "plot_int_faceted_linear": "plot_int() with explicit facet_rows, facet_cols, and scientific_10_y=False.",
    "plot_type_num_reps": "Replicate peptide-type plot with explicit x_var, facet_rows, and Protein.group colors.",
    "plot_type_num_filtered_scientific": "plot_type_num() with filter_params, facet_cols, and scientific_10_y=True.",
    "plot_count_mean_none": "plot_count() wrapper with color_by='none'.",
    "plot_count_reps_faceted": "plot_count() wrapper with replicate faceting, filter_params, and scientific_10_y=True.",
    "plot_length_bar": "Length-distribution bar plot filtered by Digest.stage.",
    "plot_length_density": "Length-distribution density plot at replicate level.",
    "plot_length_bar_named_linear": "Length-distribution bar plot with Protein.name colors, facet_cols, and scientific_10_y=False.",
    "plot_gravy_scatter": "Default GRAVY-vs-intensity scatter plot.",
    "plot_gravy_density": "Replicate-level density plot with filtering and facet_rows.",
    "plot_gravy_scatter_named": "Scatter plot with Protein.name colors, facet_cols, and custom alpha_value.",
    "plot_volcano_plain": "Plain-mode volcano plot.",
    "plot_volcano_treat_annotated": "Treat-mode volcano plot with labels and highlights.",
    "plot_volcano_custom_ylog": "Volcano plot with custom thresholds, colors, sizes, highlight styling, and y_log_scale=True.",
    "plot_pep_align_lookup_default": "Peptide-alignment plot using packaged sequence lookup and default auto sizing.",
    "plot_pep_align_mean": "Peptide-alignment plot with an explicit protein sequence and auto_size=False.",
    "plot_pep_align_ranged_labels": "Peptide-alignment plot with filter_params, x/y ranges, tick interval, and labeled sequences.",
    "plot_pep_align_reps_custom_cols": "Replicate peptide-alignment plot using renamed sequence/start/end/intensity columns.",
    "plot_pep_align_saved": "Peptide-alignment plot saved via save_file_location with custom DPI and auto-size tuning.",
    "plot_cleavage_N": "Default N-terminal cleavage logo.",
    "plot_cleavage_both_filtered": "Both-terminal cleavage logo with filtering, type_num, and replicate-mode outputs.",
    "plot_cleavage_C_keep_constant_linear": "C-terminal cleavage logo with scientific_10_y=False and drop_constant_groups=False.",
}

FUNCTION_PARAMETER_COVERAGE = {
    "load_example_protein_mapping": {
        "__call__": ["mapping_example_dataset"],
    },
    "calculate_gravy": {
        "peptide": ["calculate_gravy_examples"],
    },
    "processPeptides": {
        "peptides_file": ["process_default"],
        "intensity_columns_file": ["process_default"],
        "protein_mapping_file": ["process_default"],
    },
    "filterPeptides": {
        "result": ["filter_exact", "filter_regex", "filter_grouped", "filter_union"],
        "seqs": ["filter_exact", "filter_union"],
        "seq_pattern": ["filter_regex", "filter_grouped", "filter_union"],
        "filter_params": ["filter_grouped"],
    },
    "ttestPeptides": {
        "result": [
            "ttest_plain_main",
            "ttest_plain_reordered",
            "ttest_plain_explicit",
            "ttest_plain_pooled",
            "ttest_plain_equalvar",
            "ttest_plain_custom_adjust",
            "ttest_plain_min_reps",
            "ttest_treat_main",
            "ttest_treat_custom_threshold",
        ],
        "comparisons": [
            "ttest_plain_main",
            "ttest_plain_reordered",
            "ttest_plain_explicit",
            "ttest_plain_pooled",
            "ttest_treat_main",
        ],
        "pseudocount": ["ttest_plain_main", "ttest_plain_custom_adjust"],
        "test_method": [
            "ttest_plain_main",
            "ttest_treat_main",
            "ttest_treat_custom_threshold",
        ],
        "lfc_thresh": ["ttest_treat_main", "ttest_treat_custom_threshold"],
        "alpha": ["ttest_treat_main", "ttest_treat_custom_threshold"],
        "equal_var": ["ttest_plain_equalvar"],
        "adjust": ["ttest_plain_main", "ttest_plain_custom_adjust"],
        "min_reps_per_side": ["ttest_plain_main", "ttest_plain_min_reps"],
    },
    "plot_int": {
        "result": ["plot_int_mean_named", "plot_int_reps_default", "plot_int_faceted_linear"],
        "type": ["plot_int_mean_named", "plot_int_reps_default"],
        "x_var": ["plot_int_mean_named", "plot_int_reps_default"],
        "color_by": ["plot_int_mean_named", "plot_int_reps_default"],
        "filter_params": ["plot_int_mean_named"],
        "facet_rows": ["plot_int_faceted_linear"],
        "facet_cols": ["plot_int_reps_default", "plot_int_faceted_linear"],
        "scientific_10_y": ["plot_int_reps_default", "plot_int_faceted_linear"],
    },
    "plot_type_num": {
        "result": ["plot_type_num_reps", "plot_type_num_filtered_scientific"],
        "type": ["plot_type_num_reps"],
        "x_var": ["plot_type_num_reps"],
        "color_by": ["plot_type_num_reps"],
        "filter_params": ["plot_type_num_filtered_scientific"],
        "facet_rows": ["plot_type_num_reps"],
        "facet_cols": ["plot_type_num_filtered_scientific"],
        "scientific_10_y": ["plot_type_num_reps", "plot_type_num_filtered_scientific"],
    },
    "plot_count": {
        "result": ["plot_count_mean_none", "plot_count_reps_faceted"],
        "type": ["plot_count_mean_none", "plot_count_reps_faceted"],
        "x_var": ["plot_count_mean_none", "plot_count_reps_faceted"],
        "color_by": ["plot_count_mean_none", "plot_count_reps_faceted"],
        "filter_params": ["plot_count_reps_faceted"],
        "facet_rows": ["plot_count_reps_faceted"],
        "facet_cols": ["plot_count_reps_faceted"],
        "scientific_10_y": ["plot_count_mean_none", "plot_count_reps_faceted"],
    },
    "plot_length_distribution": {
        "result": ["plot_length_bar", "plot_length_density", "plot_length_bar_named_linear"],
        "type": ["plot_length_bar", "plot_length_density", "plot_length_bar_named_linear"],
        "metric": ["plot_length_bar", "plot_length_density"],
        "color_by": ["plot_length_bar", "plot_length_bar_named_linear"],
        "filter_params": ["plot_length_bar"],
        "facet_rows": ["plot_length_bar", "plot_length_density"],
        "facet_cols": ["plot_length_bar_named_linear"],
        "scientific_10_y": ["plot_length_bar", "plot_length_bar_named_linear"],
        "plot_mode": ["plot_length_bar", "plot_length_density"],
    },
    "plot_gravy_vs_intensity": {
        "result": ["plot_gravy_scatter", "plot_gravy_density", "plot_gravy_scatter_named"],
        "type": ["plot_gravy_scatter", "plot_gravy_density"],
        "color_by": ["plot_gravy_scatter", "plot_gravy_scatter_named"],
        "filter_params": ["plot_gravy_density"],
        "facet_rows": ["plot_gravy_density"],
        "facet_cols": ["plot_gravy_scatter_named"],
        "alpha_value": ["plot_gravy_scatter", "plot_gravy_scatter_named"],
        "plot_mode": ["plot_gravy_scatter", "plot_gravy_density"],
    },
    "plot_volcano": {
        "ttest_result": [
            "plot_volcano_plain",
            "plot_volcano_treat_annotated",
            "plot_volcano_custom_ylog",
        ],
        "comparisons": [
            "plot_volcano_plain",
            "plot_volcano_treat_annotated",
            "plot_volcano_custom_ylog",
        ],
        "test_method": [
            "plot_volcano_plain",
            "plot_volcano_treat_annotated",
            "plot_volcano_custom_ylog",
        ],
        "show_threshold": ["plot_volcano_plain", "plot_volcano_custom_ylog"],
        "lfc_thresh": ["plot_volcano_plain", "plot_volcano_custom_ylog"],
        "alpha": ["plot_volcano_plain", "plot_volcano_custom_ylog"],
        "fill_values": ["plot_volcano_plain", "plot_volcano_custom_ylog"],
        "point_size": ["plot_volcano_plain", "plot_volcano_custom_ylog"],
        "point_alpha": ["plot_volcano_plain", "plot_volcano_custom_ylog"],
        "label_seqs": ["plot_volcano_treat_annotated", "plot_volcano_custom_ylog"],
        "label_size": ["plot_volcano_treat_annotated", "plot_volcano_custom_ylog"],
        "label_col": ["plot_volcano_treat_annotated", "plot_volcano_custom_ylog"],
        "highlight_seqs": ["plot_volcano_treat_annotated", "plot_volcano_custom_ylog"],
        "highlight_size": ["plot_volcano_custom_ylog"],
        "highlight_stroke": ["plot_volcano_treat_annotated", "plot_volcano_custom_ylog"],
        "y_log_scale": ["plot_volcano_plain", "plot_volcano_custom_ylog"],
    },
    "plot_pep_align": {
        "result": [
            "plot_pep_align_lookup_default",
            "plot_pep_align_mean",
            "plot_pep_align_ranged_labels",
            "plot_pep_align_reps_custom_cols",
            "plot_pep_align_saved",
        ],
        "protein_name": [
            "plot_pep_align_lookup_default",
            "plot_pep_align_mean",
            "plot_pep_align_ranged_labels",
            "plot_pep_align_reps_custom_cols",
            "plot_pep_align_saved",
        ],
        "protein_seq": ["plot_pep_align_lookup_default", "plot_pep_align_mean"],
        "type": ["plot_pep_align_mean", "plot_pep_align_reps_custom_cols"],
        "filter_params": ["plot_pep_align_ranged_labels", "plot_pep_align_reps_custom_cols", "plot_pep_align_saved"],
        "x_interval": ["plot_pep_align_ranged_labels"],
        "seq_col": ["plot_pep_align_reps_custom_cols"],
        "start_col": ["plot_pep_align_reps_custom_cols"],
        "end_col": ["plot_pep_align_reps_custom_cols"],
        "x_range": ["plot_pep_align_ranged_labels"],
        "y_range": ["plot_pep_align_ranged_labels"],
        "intensity_col": ["plot_pep_align_reps_custom_cols"],
        "label_seq": ["plot_pep_align_ranged_labels"],
        "label_col": ["plot_pep_align_ranged_labels"],
        "auto_size": ["plot_pep_align_lookup_default", "plot_pep_align_mean", "plot_pep_align_saved"],
        "save_file_location": ["plot_pep_align_saved"],
        "save_file_dpi": ["plot_pep_align_saved"],
        "width_per_aa": ["plot_pep_align_saved"],
        "height_per_row": ["plot_pep_align_saved"],
        "min_width": ["plot_pep_align_saved"],
        "min_height": ["plot_pep_align_saved"],
    },
    "plot_cleavage_site": {
        "result": ["plot_cleavage_N", "plot_cleavage_both_filtered", "plot_cleavage_C_keep_constant_linear"],
        "terminal": ["plot_cleavage_N", "plot_cleavage_both_filtered", "plot_cleavage_C_keep_constant_linear"],
        "measure": ["plot_cleavage_N", "plot_cleavage_both_filtered"],
        "replicate_mode": ["plot_cleavage_N", "plot_cleavage_both_filtered"],
        "filter_params": ["plot_cleavage_both_filtered", "plot_cleavage_C_keep_constant_linear"],
        "scientific_10_y": ["plot_cleavage_N", "plot_cleavage_C_keep_constant_linear"],
        "drop_constant_groups": ["plot_cleavage_N", "plot_cleavage_C_keep_constant_linear"],
    },
}


ALL_PARITY_CASES = {**STRUCTURED_PARITY_CASES, **PLOT_PARITY_CASES}
